### ISSUE TITLE
Support for different `.vim` directory

### ISSUE THREAD

**Issue by linduxed** [LucHermitte/local_vimrc#11]
I'm a user of NeoVim, and I can't place a `_vimrc_local.vim` file in `$HOME/.config/nvim` and have it read in a whitelisted manner, as the documentation suggests.

Currently the the `lh#path#vimfiles` function is used to obtain the location of the Vim-file directory, [as can be seen here](https://github.com/LucHermitte/local_vimrc/blob/198d04d9ffa81d2d01e4088aa0e9a00f979e499b/autoload/lh/local_vimrc.vim#L93). I assume that this function normally returns `$HOME/.vim`, but I haven't investigated that closely.

When I try running `:call lh#path#vimfiles()` or `:echo lh#path#vimfiles()` I get no output, but I'm not sure if that's how I should check if it works. Could it be that this function is incompatible with NeoVim?

**Comment by LucHermitte** [comment]
Hi


> I'm a user of NeoVim, and I can't place a _vimrc_local.vim file in
> $HOME/.config/nvim and have it read in a whitelisted manner, as the
> documentation suggests.

Note that independently of `lh#path#vimfiles()`, you should be able to manually add `$HOME.'/.config/nvim'` to the whitelist.

> Currently the the lh#path#vimfiles function is used to obtain the
> location of the Vim-file directory, as can be seen here . I assume
> that this function normally returns $HOME/.vim , but I haven't
> investigated that closely.

Yes. It'll return either `$HOME/.vim/` or the equivalent `$HOME/vimfiles/` under Windows that is used in the `'runtimepath'` option.
I'm also able to trick it into accepting things like `$HOME/luc/.vim`. 


> Could it be that this function is
> incompatible with NeoVim?

I'm not sure how neovim works as I don't use it. What would the right directory be? Something like `$HOME/.config/nvim`?

Would it give correct results if you replace `lh#path#vimfiles()` 3rd line with:

```vim
  let what =  '\%('.re_HOME.re_LUCHOME.'\)'.'\(vimfiles\|.vim\|.config[/\\]nvim\)'
```

**Comment by linduxed** [comment]
Yes, adding that line instead of the current `let what = ...` line makes it load `~/.config/nvim/_vimrc_local.vim` automatically, in a whitelisted fashion.

**Comment by LucHermitte** [comment]
Thank you.

**Comment by linduxed** [comment]
Thanks for the quick fix!
