### ISSUE TITLE
Does this work with vim 8?

### ISSUE THREAD

**Issue by mkarpoff** [LucHermitte/local_vimrc#13]
I'm looking for something like this but I currently use vim 8.0 I was wondering if this would still work fully with vim 8. Does it work with the vim 8 package maanger?

**Comment by LucHermitte** [comment]
Hi,

I'm currently using vim 8.559. So yes it work with Vim 8.
Regarding packages, I'm not using them for now -- I expect more of my plugin manager: to support dependencies.

Out of the box, I see no reason why you couldn't bundle this plugin in a vim 8 package.

**Comment by mkarpoff** [comment]
Thanks for the speedy answer. I'll give it a go then.

**Comment by LucHermitte** [comment]
Let me know if you experience any difficulty.
