### ISSUE TITLE
What does "Always" do?

### ISSUE THREAD

**Issue by rddunphy** [LucHermitte/local_vimrc#19]
When I open a file which has a `_vimrc_local.vim` in the same directory (a subdirectory of `$HOME`, so by default it behaves as if it's in `asklist`), I get a prompt asking if I want to recognise it. If I select "Always" and hit enter, the local vimrc is sourced, but when I close my file and reopen it, I get the same prompt again, as if I'd just entered "Yes". I assumed that instead, it would add the local vimrc to the whitelist so that I don't get prompted again. Am I misunderstanding what the "Always" option is meant to do? Do I need to add it to the whitelist in my `.vimrc`?

**Comment by LucHermitte** [comment]
Just to be sure what you mean by _close my file and reopen it_: Do you close Vim? Or do you just close the file with `:q` (and still have Vim opened), or may be even `bdelete` or `bwipe`  it?
 
The intended behaviour of the _asklist_ is to remember the choice made on a buffer in a same Vim session.

**Comment by rddunphy** [comment]
Ah, okay - thanks for the reply! I meant when I close Vim; I couldn't see any documentation on it, and intuitively it seemed like choosing "always" should make the setting persistent between sessions. Manually adding the directory to the whitelist does what I want.
