### ISSUE TITLE
Usage of `LetIfUndef` with `lh-vim-lib` 4.0.0 breaks

### ISSUE THREAD

**Issue by linduxed** [LucHermitte/local_vimrc#8]
[This line](https://github.com/LucHermitte/local_vimrc/blob/4369d918ed29db02d8c10df98d72165881cfe820/plugin/local_vimrc.vim#L131) breaks with the latest version of [`lh-vim-lib`](https://github.com/LucHermitte/lh-vim-lib) (at least that's what I think is happening). It was introduced in 30f837f11e4bafdfc1e9bff7c986f54c3b063a86.

The following error is produced when one starts Vim:
```plain
Error detected while processing function lh#let#if_undef:
line   11:
E605: Exception not caught: Cannot set ['g:local_vimrc_options._do_handle  { file -> execute(''source ''.escape(file, '' \$''))}']: Vim(let):E15: Invalid expression: > execute('source '.escape(file, ' \$'))} @ function lh#let#if_undef[3]..<SNR>143_BuildPublicVariableNameAndValue, line 12
```

**Comment by LucHermitte** [comment]
Sorry. My mistake.

I'm trying to fix and update some other plugins and on my way I've used 2 new features from latest versions of Vim (lambdas and `execute()`). This "regression" should be fixed now.
