### ISSUE TITLE
tuning list statements seems not working well with vundle

### ISSUE THREAD

**Issue by Qiguang** [LucHermitte/local_vimrc#9]
Hi, I am trying to use this cool plugin. every time I enter the directory which contain _vimrc_local.vim, vim asks me "Do you want to recognize a local vimrc at "/the/dir/_vimrc_local.vim"?". And I tried to add this directory to white list. I just did as the README.md file says. added
"**call lh#path#munge(g:local_vimrc_options.whitelist, $HOME.'/my/dir')**" to my .vimrc in the position after the plugins(LucHermitte/lh-vim-lib, LucHermitte/local_vimrc) loaded by vundle. but every time I launch vim, it prompts 
**"Error detected while processing /home/robin/.vim/vimrc:
line  129:
E121: Undefined variable: g:local_vimrc_options
E116: Invalid arguments for function lh#path#munge"**
in my .vimrc, the plugin loading statements of vundle is 
"
**Plugin 'LucHermitte/lh-vim-lib'
Plugin 'LucHermitte/local_vimrc'**
"
is this an issue or I did some thing wrong?
thanks.

**Comment by LucHermitte** [comment]
Hi,

> is this a issue or I did some thing wrong?
> thanks.

No this is something I need to document/improve.

Before defining the lists in your .vimrc, add a first

```vim
" either
let g:local_vimrc_options = get(g:, 'local_vimrc_options', {})

" or the equivalent (here)
runtime plugin/let.vim
LetIfUndef g:local_vimrc_options = {}
```


It should work better after that.

**Comment by Qiguang** [comment]
I have tried the first option.
In my .vimrc, it's
**let g:local_vimrc_options=get(g:,"local_vimrc_options",{})
call lh#path#munge(g:local_vimrc_options.whitelist, $HOME)**
But when I launch vim, it prompts
**Error detected while processing /home/robin/.vim/vimrc:
line  132:
E716: Key not present in Dictionary: whitelist, $HOME)
E116: Invalid arguments for function lh#path#munge
Press ENTER or type command to continue**
Then, I tried to add
**let g:local_vimrc_options.whitelist = []**
between the 2 statements above.
It works.

**Comment by LucHermitte** [comment]
Indeed you're right.

In order to simplify the management of the permission lists, I've added 3 functions and you won't need to initialize these variable anymore.

You should be able to directly write:
```vim
call lh#local_vimrc#munge('whitelist', $HOME)
" and in order to clear your asklist::
call lh#local_vimrc#filter_list('asklist', 'v:val != $HOME')
```
